name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

resources:
  containers:
    - container: 'ubuntu_container_for_build_deply_to_nexus'
      image: 'ubuntu:latest'
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      ref: refs/tags/1.1.22
      endpoint: statisticsnorway (6)

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Hemmeligheter
  - name: fullSha
    value: '$(Build.SourceVersion)'
  - name: imageName
    value: 'eu.gcr.io/prod-bip/data-collector'
  - name: repoName
    value: 'prod-bip/data-collector'
  - name: MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MAVEN_OPTS
    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

jobs:
  - template: complete-builds/job-test-integration-coverage-build-gcr.yml@templates
    parameters:
      project: dapla
      imageName: $(imageName)
      repoName: $(repoName)
      artifactName: data-collector
      checkStyleRunAnalysis: false
      mavenServices:
        pubsub: pubsub_container

  - template: docker/docker-tag-for-production.yml@templates
    parameters:
      tagToTag: 'master-$(fullSha)'
      gcrImageName: ${{ variables.imageName }}
