FROM statisticsnorway/alpine-jdk13-buildtools:latest as build

#
# Build DC Backend
#


#
# Build DC image
#
FROM alpine:latest

RUN apk add --no-cache bash curl openssl

#
# Resources from build image
#
COPY --from=build /opt/jdk /opt/jdk/
COPY target/dependency /opt/dc/lib/
COPY target/data-collector-*.jar /opt/dc/lib/

ADD docker/boostrap-dev.sh /run.sh
RUN chmod +x /run.sh

ENV PROXY_HOST=
ENV PROXY_PORT=

ENV PATH=/opt/jdk/bin:$PATH
ENV JAVA_HOME=/opt/jdk

WORKDIR /opt/dc

VOLUME ["/conf", "/certs"]

EXPOSE 9990
EXPOSE 9992

CMD ["/run.sh"]
