FROM statisticsnorway/lds-server-base:latest as build

#
# Build DC Backend
#
RUN ["jlink", "--strip-debug", "--no-header-files", "--no-man-pages", "--compress=2", "--module-path", "/opt/jdk/jmods", "--output", "/linked",\
 "--add-modules", "jdk.unsupported,java.base,java.management,java.net.http,java.xml,java.naming,java.sql,java.desktop,java.security.jgss,java.instrument,jdk.internal.vm.compiler,jdk.management.agent"]

#
# Build DC image
#
FROM alpine:latest

RUN apk add --no-cache curl openssl

#
# Resources from build image
#
COPY --from=build /linked /opt/jdk/
COPY target/dependency /opt/dc/lib/
COPY target/data-collector-*.jar /opt/dc/lib/

ENV PATH=/opt/jdk/bin:$PATH

WORKDIR /opt/dc

VOLUME ["/conf", "/certs"]

EXPOSE 9990
EXPOSE 9992

CMD ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+EnableJVMCI", "-Dcom.sun.management.jmxremote.rmi.port=9992", "-Dcom.sun.management.jmxremote=true", "-Dcom.sun.management.jmxremote.port=9992", "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.authenticate=false", "-Dcom.sun.management.jmxremote.local.only=false", "-Djava.rmi.server.hostname=localhost", "-p", "/opt/dc/lib", "-m", "no.ssb.dc.server/no.ssb.dc.server.Server"]
